### ISSUE TITLE
Location of hardware design files since marketed as "Open Hardware"

### ISSUE THREAD

**Issue by pdp7** [96boards/linux-hikey#1]
The phrase "Open Hardware Boards" is used in large font size at the top of the 96boards.org website:
https://www.96boards.org/

This implies that the 96boards.org boards including the HiKey are Open Hardware (e.g. Open Source Hardware).  Such a product should release the design files (schematics, PCB board layout and Bill of Materials) under an Open Source license: http://www.oshwa.org/faq/

Are the design files available online?

thanks,
drew

**Comment by koenkooi** [comment]
No, schematics only, no design files or BOM. While you are correct that it isn't open hardware, I'm going to close this bug since it's not related to the kernel. Can you please share your concerns through https://www.96boards.org/contact/ ?
